### ISSUE TITLE
key checking - and exe file completion, version check of bin files

### ISSUE THREAD

**Issue by Leerz** [imPRAGMA/LFSKit#2]
deletion of files from unifinished extraction/patching of bin files causes error. 
ex. main bin file to kernal patch region - (usually caused by unsupported main bin file of lower versions)

version check would be good too, 
ie. 5x dump and 4x dump -
i'd like to help, but i'm pretty rusty with coding

also it would be nice to put on on the msgbox when files are about to be copied to the sd - 
just a reminder that no files will be deleted, only copied - some peeps are paranoid when they accidentally click on a local drive 

Thanks for this!

**Comment by imPRAGMA** [comment]
This is good now then right? Since kernel-patching isnt used anymore.
